// Auto-generated by optimize_classifier.py
// DO NOT EDIT MANUALLY

#pragma once
#include <array>
#include <cmath>

struct OptimizedCoefficients {
    static constexpr float kConfidenceThreshold = 0.7f;

    // Lighting Difference
    static constexpr float kLighting_Difference[] = { 3.000f, 0.971f, 0.224f, 0.244f, 0.225f, 0.265f, 0.068f };

    // Shadow Difference
    static constexpr float kShadow_Difference[] = { 3.042f, 2.000f, 0.396f, 0.150f, 0.500f };

    // Bloom Difference
    static constexpr float kBloom_Difference[] = { 3.142f, 2.000f, 0.382f, 0.150f, 0.500f };

    // Reflection Difference
    static constexpr float kReflection_Difference[] = { 1.029f, 2.000f, 1.021f, 1.040f, 0.133f, 0.305f };

    // Texture Difference
    static constexpr float kTexture_Difference[] = { 1.530f, 1.016f, 0.258f, 0.100f, 0.255f };

    // Material Difference
    static constexpr float kMaterial_Difference[] = { 1.473f, 1.308f, 1.310f, 0.150f, 0.391f };

    // Transparency Difference
    static constexpr float kTransparency_Difference[] = { 1.356f, 1.173f, 1.272f, 0.436f, 0.074f, 0.378f };

    // Edge Difference
    static constexpr float kEdge_Difference[] = { 2.593f, 0.963f, 0.257f, 0.226f, 0.009f };

    // Missing Geometry
    static constexpr float kMissing_Geometry[] = { 0.600f, 0.800f, 1.600f, 0.200f, 0.344f };

    // Extra Geometry
    static constexpr float kExtra_Geometry[] = { 1.331f, 1.325f, 1.196f, 0.200f, 0.100f };

    // Missing Object
    static constexpr float kMissing_Object[] = { 0.781f, 1.273f, 1.267f, 0.200f, 0.100f, 0.371f };

    // Missing Particle
    static constexpr float kMissing_Particle[] = { 1.386f, 1.233f, 0.300f, 0.374f, 0.100f, 0.100f };

    // Missing UI
    static constexpr float kMissing_UI[] = { 0.164f, 1.077f, 0.362f, 0.368f, 0.100f, 0.244f };

    // Text Difference
    static constexpr float kText_Difference[] = { 1.322f, 1.239f, 0.200f, 0.500f, 0.347f, 0.100f };

    // Stereo Offset
    static constexpr float kStereo_Offset[] = { 1.252f, 1.182f, 0.499f, 0.498f, 0.007f, 0.162f };

    // Depth/Disparity Error
    static constexpr float kDepth_Disparity_Error[] = { 1.500f, 0.300f, 0.150f, 0.100f, 0.100f };

    // Occlusion Difference
    static constexpr float kOcclusion_Difference[] = { 1.287f, 1.220f, 0.500f, 0.200f, 0.500f };

    // Post Process Difference
    static constexpr float kPost_Process_Difference[] = { 1.465f, 1.306f, 1.372f, 0.386f, 0.500f, 0.346f };

    // Temporal Difference
    static constexpr float kTemporal_Difference[] = { 1.500f, 0.200f, 0.150f, 0.100f };

    // Lens Boundary
    static constexpr float kLens_Boundary[] = { 0.686f, 0.200f, 0.104f, 0.314f };

    // Platt scaling parameters
    struct PlattParam { float a; float b; };
    static constexpr PlattParam kPlattParams[] = {
        { 4.1473f, -6.5578f },  // Lighting Difference
        { 3.5794f, -5.7709f },  // Shadow Difference
        { 4.7733f, -5.7844f },  // Bloom Difference
        { 0.1856f, -3.0686f },  // Reflection Difference
        { 3.0415f, -5.4818f },  // Texture Difference
        { 2.3180f, -4.8911f },  // Material Difference
        { 5.1751f, -7.4975f },  // Transparency Difference
        { 0.4254f, -3.1451f },  // Edge Difference
        { 2.0343f, -4.2017f },  // Missing Geometry
        { 208.5163f, -211.6138f },  // Extra Geometry
        { 4.4479f, -7.5501f },  // Missing Object
        { 820.2735f, -823.2503f },  // Missing Particle
        { 2060.7217f, -2063.1568f },  // Missing UI
        { 0.0973f, -2.7963f },  // Text Difference
        { 1247.0051f, -1248.5679f },  // Stereo Offset
        { -8391.1273f, 6.5792f },  // Depth/Disparity Error
        { -1.0411f, -2.1017f },  // Occlusion Difference
        { -0.8205f, -2.3895f },  // Post Process Difference
        { -5218.8314f, -39.0577f },  // Temporal Difference
        { 3349.4941f, -3350.8551f },  // Lens Boundary
    };

    static float applyPlattScaling(int typeIndex, float rawScore) {
        if (typeIndex < 0 || typeIndex >= 20) return rawScore;
        const auto& p = kPlattParams[typeIndex];
        return 1.0f / (1.0f + std::exp(-(p.a * rawScore + p.b)));
    }
};
